export const artworks = [
    {
      id: 1,
      title: "Mizuno Noah",
      category: "Ilustração",
      year: "2023",
      description: "Mizuno Noah, is my new OC, with a futuristic cyberpunk look, another 1 from the drop of a project that will soon be 4 you!! THX.",
      image: "/assets/artworks/Mizuno_Noah.png",
      tags: ["Cyberpunk", "Art", "Fantasy", "Digital", "Mangá"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#F44336"
    },
    {
      id: 2,
      title: "Takahashi Hayato",
      category: "Ilustração",
      year: "2023",
      description: "Takahashi Hayato, is my new OC, with a futuristic cyberpunk look, another 1 from the drop of a project that will soon be 4 you!! THX <3.",
      image: "/assets/artworks/Hayato Takahashi.png",
      tags: ["Cyberpunk", "Art", "Fantasy", "Digital", "Mangá"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#00CED1"
    },
    {
      id: 3,
      title: "CyberGirl",
      category: "Ilustração",
      year: "2024",
      description: "Retrato estilizado com elementos de cultura pop e neon.",
      image: "/assets/artworks/CyberGirl.png",
      tags: ["Cyberpunk", "Art", "Fantasy", "Digital", "Mangá"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#FF1493"
    },
    {
      id: 4,
      title: "Yoshida Aiko",
      category: "Ilustração",
      year: "2022",
      description: "Estudo de formas naturais com técnicas mistas em papel.",
      image: "/assets/artworks/Toxic_Girl.png",
      tags: ["Sketch", "Nature", "Ink"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#32CD32"
    },
    {
      id: 5,
      title: "Miyazaki Miki",
      category: "Ilustração",
      year: "2024",
      description: "Miyazaki Miki, is my new OC, with a futuristic cyberpunk look, another 1 from the drop of a project that will soon be 4 you!! THX <3",
      image: "/assets/artworks/Miki_Miyazaki2.png",
      tags: ["Cyberpunk", "Art", "Fantasy", "Digital", "Mangá"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#9370DB" 
    },
    {
      id: 6,
      title: "Jett",
      category: "Ilustração",
      year: "2023",
      description: "Jett fanart, because is the best agent and my main in Valorant.",
      image: "/assets/artworks/Jett_Fanart.png",
      tags: ["Art", "Digital", "Valorant", "Fanart", "Draw"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#00CED1" 
    },
    {
      id: 7,
      title: "Fish Smoking",
      category: "Cartoon",
      year: "2020",
      description: "A espada parcialmente visível revela um possível passado de lutas ou uma natureza defensiva, enquanto seu olhar fixo em algo intriga uma história oculta por trás dessa presença incomum.",
      image: "/assets/artworks/Desafio Draw This In Your Style.png",
      tags: ["Cartoon", "Art", "Fish", "Digital", "Smoke"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#FF6347"
    },
    {
      id: 8,
      title: "Solidão Noturna",
      category: "Cartoon",
      year: "2020",
      description: "Sob o olhar da lua crescente em uma noite estrelada, um garoto contempla a solidão e o vazio das ruas de uma cidade. O contraste entre o calor das janelas e o brilho frio do neon emoldura um momento de quietude e reflexão em meio à paisagem urbana noturna.",
      image: "/assets/artworks/SolidãoEscura.png",
      tags: ["Cyberpunk", "Surreal", "Fantasy", "Digital", "Mangá"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#9370DB"
    },
    {
      id: 9,
      title: "Jasgreen",
      category: "Ilustração",
      year: "2024",
      description: "",
      image: "/assets/artworks/Day_One_Green2.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#32CD32"
    },
    {
      id: 10,
      title: "Woe",
      category: "Cartoon",
      year: "2021",
      description: "A luz bruxuleante das lanternas mal ilumina a chuva torrencial que emoldura um portal enigmático. Em meio a este cenário melancólico, um personagem solitário segue seu caminho, carregando consigo a promessa de uma história a ser descoberta.",
      image: "/assets/artworks/WOE.png",
      tags: ["Vector", "Portrait", "Pop Art"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#FF1493"
    },
    {
      id: 11,
      title: "I.M.P.O.S.T.O.R",
      category: "Ilustração",
      year: "2020",
      description: "",
      image: "/assets/artworks/I.M.P.O.S.T.OR.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#00CED1" 
    },
    {
      id: 12,
      title: "NikeBoy",
      category: "Cartoon",
      year: "2021",
      description: "",
      image: "/assets/artworks/NIKEBOY.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#FF6347"
    },
    {
      id: 13,
      title: "Adventure Girl",
      category: "Ilustração",
      year: "2021",
      description: "Entre o calor da fogueira e a frieza da noite, uma garota se encontra um momento de descanso. A máscara e a espada contrastam com a garrafa d'água  revelando o caminho para uma aventura em um mundo incerto.",
      image: "/assets/artworks/Adventure.png",
      tags: ["Digital Art", "Space", "Abstract"],
      softwares: ["Clip Studio Paint", "Wacom CTL-472"],
      accentColor: "#8A2BE2"
    },
    {
      id: 14,
      title: "Jeff the Killer",
      category: "Ilustração",
      year: "2021",
      description: "",
      image: "/assets/artworks/JeffTheKiller2.png",
      tags: ["Collage", "Typography", "City"],
      softwares: ["Clip Studio Paint", "Wacom CTL-472"],
      accentColor: "#00CED1"
    },
    {
      id: 15,
      title: "BahiaMan",
      category: "Ilustração",
      year: "2022",
      description: "",
      image: "/assets/artworks/BahiaMan.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#FF6347"
    },
    {
      id: 16,
      title: "Path (Day 3 Inktober)",
      category: "Ink Art",
      year: "2023",
      description: "",
      image: "/assets/artworks/Path_Day_3_Inktober.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#FF6347"
    },
    {
      id: 17,
      title: "Scorn in Subway",
      category: "Ilustração",
      year: "2021",
      description: "",
      image: "/assets/artworks/scorn_subway.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#00CED1" 
    },
    {
      id: 18,
      title: "Gaara (Naruto Hype)",
      category: "Cartoon",
      year: "2021",
      description: "",
      image: "/assets/artworks/GAARA.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#FF6347"
    },
    {
      id: 19,
      title: "Spiders (Day 2 Inktober)",
      category: "Ink Art",
      year: "2023",
      description: "",
      image: "/assets/artworks/Spiders_Day_2_Inktober.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#FF6347"
    },
    {
      id: 20,
      title: "Poster PlanetBurger",
      category: "Design Gráfico",
      year: "2020",
      description: "",
      image: "/assets/artworks/PlanetBurguer.jpg",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#FF6347"
    },
    {
      id: 21,
      title: "Tobi (Naruto Hype)",
      category: "Cartoon",
      year: "2021",
      description: "",
      image: "/assets/artworks/TOBI.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#FF6347"
    },
    {
      id: 22,
      title: "MorusuSamurai",
      category: "Ilustração",
      year: "2024",
      description: "",
      image: "/assets/artworks/Photo_Morusu_Steam.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#FF6347"
    },
    {
      id: 23,
      title: "Finn & Jake",
      category: "Cartoon",
      year: "2020",
      description: "Fanart vibrante de Finn e Jake em plena aventura! Cores saturadas e linhas dinâmicas capturam a energia inconfundível da dupla de 'Adventure Time' em um momento cheio de fantasia e movimento.",
      image: "/assets/artworks/finnAndJake.jpg",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#8A2BE2"
    },
    {
      id: 24,
      title: "Dodge (Day 4 Inktober)",
      category: "Ink Art",
      year: "2023",
      description: "",
      image: "/assets/artworks/Dodge_Day_4_Inktober.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#FF6347"
    },
    {
      id: 25,
      title: "Map (Day 5 Inktober)",
      category: "Ink Art",
      year: "2023",
      description: "",
      image: "/assets/artworks/Map_Day_5_Inktober.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Clip Studio Paint", "XP-Pen Artist 12 Pro"],
      accentColor: "#FF6347"
    },
    {
      id: 26,
      title: "Spike the Cactus",
      category: "Ilustração",
      year: "2023",
      description: "",
      image: "/assets/artworks/cactusSpike.png",
      tags: ["Minimal", "Geometry", "Poster"],
      softwares: ["Photoshop", "Wacom CTL-472"],
      accentColor: "#FF6347"
    }
  ];